"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['Database.py',
 'EditTopics.py',
 'EditVisit.py',
 'Export_CSV.py',
 'NewStudent.py',
 'NewVisit.py',
 'Widgets.py',
 'cup.db',
 'data.sql',
 'gui_list.py',
 'gui_search.py',
 'gui_student.py',
 'main.py',
 'option.py',
 'schema.sql']
OPTIONS = {'iconfile': '/Users/macbook/Desktop/Dev/CSC271Final/fin project/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
